# -*- coding: utf-8 -*-
"""python3_exercicios_map,reduce,filter,list_comprehension,enumerate,erros_e_excecoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkXjhV6MVjXhkiw-BNLcZth1E16zkdJi

# Função reduce()
Lista de exercícios resolvidos voltados ao uso da função built-in **reduce()** utilizando a Linguagem Python

1. Use reduce() para imprimir o produto desses números
"""

from functools import reduce

#Dados
my_numbers = [4, 6, 9, 23, 5]

#Resolução
reduce(lambda num1, num2: num1 * num2, my_numbers)